def print_menu():
    print("\n")
    print(" '1' to GET NUMBER OF VERTICES")
    print(" '2' to ITERATE SET OF VERTICES")
    print(" '3' to CHECK IF THERE IS AN EDGE FOR A GIVEN VERTEX TO ATOTHER")
    print(" '4' to GET THE IN DEGREE AND OUT DEGREE OF A VERTEX")
    print(" '5' to ITERATE THE SET OF OUTBOUND EDGES OF A VERTEX")
    print(" '6' to ITERATE THE SET OF INBOUND EDGES OF A VERTEX")
    print(" '7' to GET THE COST OF A GIVEN EDGE")
    print(" '8' to MODIFY THE COST OF A GIVEN EDGE")
    print(" '9' to ADD AN EDGE")
    print("'10' to REMOVE AN EDGE")
    print("'11' to ADD A VERTEX")
    print("'12' to REMOVE A VERTEX")
    print("'13' to COPY THE GRAPH")
    print("'14' to RESTORE THE COPY OF THE GRAPH")
    print("'15' to WRITE GRAPH TO 'graph.txt'")
    print("'16' to ITERATE ALL EDGES")
    print("'17' BACKWARDS BFS")
    print("'18' BELLMAN-FORD")
    print("'19' CHECK IF GRAPH IS DAG (FIND HIGHEST COST PATH BETWEEN TWO VERTICES)")
    print(" '0' to EXIT")
    print("\n")